spring.application.name=StudentGrader

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Database (use Railway env vars)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


# Hot reload (local only, won't matter in Railway)
spring.devtools.restart.enabled=true

# Mail configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
